[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Ghazal"
  pageRef = "ghazals"
  weight = 20

[[main]]
  name = "Nazm"
  pageRef = "nazms"
  weight = 30

[[main]]
  name = "Kavita"
  pageRef = "kavita"
  weight = 40

[[main]]
  name = "Poets"
  pageRef = "poets"
  weight = 50

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 60

[[main]]
  name = "About"
  pageRef = "about"
  weight = 70
