[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Ghazals"
  pageRef = "ghazals"
  weight = 30

[[main]]
  name = "Poets"
  pageRef = "poets"
  weight = 40
